### ISSUE TITLE
Testing removal of maintainer label on author closing the issue

### ISSUE THREAD

**Issue by Programmer404NotFound** [MBilalShafi/test-github-action#5]
Whenever there's a `waiting for maintainer` label and author (comments + ) or simply closes the issue, the `waiting for maintainer` label should be removed as it doesn't make sense anymore.

**Comment by MBilalShafi** [comment]
Could you attach another comment please?

**Comment by Programmer404NotFound** [comment]
Sure, here you go.

**Comment by Programmer404NotFound** [comment]
I feel there's no further action needed on this ticket, I'll go ahead and close it! Which should also remove the label about `maintainer's response`.
