### ISSUE TITLE
Testing the removal of maintainer label on author closing the issue

### ISSUE THREAD

**Issue by Programmer404NotFound** [MBilalShafi/test-github-action#6]
Whenever there's a waiting for maintainer label and author (comments + ) or simply closes the issue, the waiting for maintainer label should be removed as it doesn't make sense anymore.

**Comment by MBilalShafi** [comment]
Hello @Programmer404NotFound, could you explain as per the latest [update](https://github.com/MBilalShafi/no-response-add-label/pull/1) in the action, what should happen when an author closes an issue that he reported and it has a label `waiting for maintainer's response` label?

**Comment by Programmer404NotFound** [comment]
Yep sure.

The label `waiting for maintainer's response` should be removed as it doesn't make sense anymore because the issue author closed the issue, i.e. the problem is not there anymore.

I'll do a `Close with comment` on this one to see if it works as expected.

**Comment by Programmer404NotFound** [comment]
Testing the other scenario now, if the `waiting for author's response` is added to the issue, and author does a `Close with comment`, the other label `waiting for maintainer's response` should not be added to begin with, and `waiting for author's response` should be removed too.

Doing another close with comment!
