### ISSUE TITLE
Another test

### ISSUE THREAD

**Issue by Programmer404NotFound** [MBilalShafi/test-github-action#7]

**Comment by MBilalShafi** [comment]
Hello, please attach some information

**Comment by Programmer404NotFound** [comment]
I just wanted to test the workflow

**Comment by Programmer404NotFound** [comment]
This `close with comment` should clear up the labels on this issue

**Comment by Programmer404NotFound** [comment]
This `close with comment` should clear up the labels on this issue

**Comment by MBilalShafi** [comment]
Now test the other way around, with a waiting for author's response added. Just do another close with comment.

**Comment by Programmer404NotFound** [comment]
Sure, here you go!

**Comment by MBilalShafi** [comment]
Another close with comment

**Comment by Programmer404NotFound** [comment]
Close with comment
